config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :droids

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/droid.rb
class Droid < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/droids_controller.rb
class DroidsController < InheritedResources::Base
  private

    def droid_params
      params.require(:droid).permit(:droid_name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/droids_helper.rb
module DroidsHelper
end

app/views/droids/_form.html.erb
<%= form_for(@droid) do |f| %>
  <% if @droid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@droid.errors.count, "error") %> prohibited this droid from being saved:</h2>

      <ul>
      <% @droid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :droid_name %><br>
    <%= f.text_field :droid_name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/droids/edit.html.erb
<h1>Editing Droid</h1>

<%= render 'form' %>

<%= link_to 'Show', @droid %> |
<%= link_to 'Back', droids_path %>

app/views/droids/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Droids</h1>

<table>
  <thead>
    <tr>
      <th>Droid name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @droids.each do |droid| %>
      <tr>
        <td><%= droid.droid_name %></td>
        <td><%= droid.price %></td>
        <td><%= link_to 'Show', droid %></td>
        <td><%= link_to 'Edit', edit_droid_path(droid) %></td>
        <td><%= link_to 'Destroy', droid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Droid', new_droid_path %>

app/views/droids/new.html.erb
<h1>New Droid</h1>

<%= render 'form' %>

<%= link_to 'Back', droids_path %>

app/views/droids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Droid name:</strong>
  <%= @droid.droid_name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @droid.price %>
</p>

<%= link_to 'Edit', edit_droid_path(@droid) %> |
<%= link_to 'Back', droids_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Droidstore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>